#!/usr/bin/env python
r"""Run Exaflow algorithms from the command line


USAGE

    ./run_analysis [-h] -a ALGORITHM -y Y [Y ...] [-x X [X ...]]
        -d DATASETS [DATASETS ...] -m DATA_MODEL [-p PARAMETER PARAMETER] [-n]

    echo <json> | ./run_analysis [-h] -a ALGORITHM [-y Y [Y ...]] [-x X [X ...]]
        [-d DATASETS [DATASETS ...]] [-m DATA_MODEL] [-p PARAMETER PARAMETER] [-n]

    ./run_analysis --doc


DESCRIPTION

    The first form is used when you want to pass all algorithm args from the
    command line. In this form some args are required and some are optional,
    according to the algorithm specifications.

    In the second form, <json> is a valid json string. Using this form you can
    pipe a json string with the algorithm args to the script, to avoid writing
    them on the command line. In this form, only the ALGORITHM arg is required
    and all other args are optional. If any other arg is passed from the
    command line it overrides the corresponding field in <json>.

    The third form prints the documentation.


ARGUMENTS

    -a, --algorithm
        The algorithm name. This is required in both forms.

    -y
        One or more space-separated fields to include in the Y variable.

    -x
        One or more space-separated fields to include in the X variable.

    -d, --datasets
        One or more space-separated dataset names.

    -m, --data-model
        The data model name in full form, NAME:VERSION.

    -p, --parameter
        A key value pair for an algorithm parameter. We can supply multiple
        parameters by repeating the '-p <key> <value>' sequences. Parameter
        values can be of types bool, int, float and str.

    --preprocessing-json
        A preprocessing step as a JSON object. Can be repeated; order is
        preserved. Example:

        --preprocessing-json '{"name":"missing_values_handler","parameters":{"strategies":{"lefthippocampus":"drop"}}}'

    -n, --dry-run
        Print request object without making actual request.

    -h, --help
        Print short help.

    --doc
        Print documentation. Cannot be combined with any other arg.


USING PIPED DATA

    The second form can be used with any program that outputs a valid json
    object, not only echo. For example you can keep the appropriate object in a
    file and use

        cat file.json | ./run_analysis ...

    The json format has to be identical to the one defined in the algorithm
    specs file.

    One useful use case is to run a particular test case from the expected json
    file, e.g. when trying to debug a particular test that failed. This can be
    done using the jq program (https://stedolan.github.io/jq/) which can search
    through a json file and filter some substructure.

    For example, you can run test case number 3 found in expected.json like this

        jq '.test_cases[3].input' expected.json | ./run_analysis ...

    Since the algorithms always return their results in json format you can
    also filter the output for a particular field. For example, running the
    first test case of the PCA algorithm, you want to see only the resulting
    eigenvalues

        jq '.test_cases[0].input' expected.json | ./run_analysis -a pca \
            | jq '.eigenvalues'

    When running a particular test case, if you want to change the value of
    some argument you can supply it after ./run_analysis. The supplied value
    will override the value found in the json data structure. For example, if
    you want the same variables and parameters, but a different dataset

        jq '.test_cases[0].input' expected.json | ./run_analysis -a pca -d ppmi0


ALGORITHM EXAMPLES

    Examples of valid algorithm inputs

    PEARSON CORRELATION

        ./run_analysis -a pearson_correlation -y leftamygdala lefthippocampus \
            -d ppmi0 -m dementia:0.1 -p alpha 0.95

    PCA

        ./run_analysis -a pca -y leftamygdala lefthippocampus -d ppmi0 \
            -m dementia:0.1

    ONE WAY ANOVA

        ./run_analysis -a anova_oneway -x ppmicategory -y lefthippocampus \
            -d ppmi1 -m dementia:0.1

    TWO WAY ANOVA
        ./run_analysis -a anova -x ppmicategory gender -y lefthippocampus \
            -d ppmi1 -m dementia:0.1 -p sstype 2

    LINEAR REGRESSION

        ./run_analysis -a linear_regression -y righthippocampus \
            -x lefthippocampus leftamygdala -d ppmi0 -m dementia:0.1

    LINEAR REGRESSION CROSS-VALIDATION

        ./run_analysis -a linear_regression_cv -y righthippocampus \
            -x lefthippocampus leftamygdala -d ppmi0 -m dementia:0.1 -p n_splits 4

    LOGISTIC REGRESSION

        ./run_analysis -a logistic_regression -y ppmicategory \
            -x lefthippocampus leftamygdala -d ppmi0 ppmi1 -m dementia:0.1 \
            -p positive_class PD

    LOGISTIC REGRESSION CROSS-VALIDATION

        ./run_analysis -a logistic_regression_cv -y gender \
            -x lefthippocampus righthippocampus -d ppmi0 ppmi1 -m dementia:0.1 \
            -p n_splits 4 -p positive_class F

    T-TEST ONE-SAMPLE
        ./run_analysis -a ttest_onesample -y lefthippocampus -d ppmi0 -m dementia:0.1 \
            -p alt_hypothesis two-sided -p alpha 0.95 -p mu 0

    T-TEST PAIRED
        ./run_analysis -a ttest_paired -y lefthippocampus -x righthippocampus \
           -d ppmi0 -m dementia:0.1 -p alt_hypothesis two-sided -p alpha 0.95
"""

import json
import pydoc
import sys
from argparse import ArgumentParser
from argparse import ArgumentTypeError

import requests

ANALYSIS_URL = "http://127.0.0.1:5100/analysis"


def parse_argv(argv):
    parser = ArgumentParser(
        prog=f"{sys.argv[0]}",
        epilog=f"To see full documentation run {sys.argv[0]} --doc.",
    )
    required_when_tty = sys.stdin.isatty()
    parser.add_argument(
        "-a",
        "--algorithm",
        required=True,
        help="Algorithm name",
    )
    parser.add_argument(
        "-y",
        required=required_when_tty,
        nargs="+",
        help="Y variables, multiple values",
    )
    parser.add_argument(
        "-x",
        required=False,
        nargs="+",
        help="X variables, multiple values",
    )
    parser.add_argument(
        "-d",
        "--datasets",
        required=required_when_tty,
        nargs="+",
        help="Datasets, multiple values",
    )
    parser.add_argument(
        "-m",
        "--data-model",
        required=required_when_tty,
        help="Data model, full name NAME:VERSION",
    )
    parser.add_argument(
        "-p",
        "--parameter",
        required=False,
        nargs=2,
        action="append",
        dest="parameters",
        help="Parameter as key value pair. Can repeat '-p key value' multiple times.",
    )
    parser.add_argument(
        "--preprocessing-json",
        required=False,
        action="append",
        dest="preprocessing",
        type=parse_preprocessing_step_json,
        help=(
            "Preprocessing step JSON object. Can repeat this option multiple "
            "times; request order is preserved."
        ),
    )
    parser.add_argument(
        "-n",
        "--dry-run",
        required=False,
        action="store_true",
        help="Print request object without making actual request.",
    )
    parser.add_argument(
        "-f",
        "--flag",
        required=False,
        nargs=2,
        action="append",
        dest="flags",
        help="Flags as key value pair. Can repeat '-f key value' multiple times.",
    )
    return parser.parse_args(argv)


def parse_preprocessing_step_json(value: str) -> dict:
    try:
        step = json.loads(value)
    except json.JSONDecodeError as exc:
        raise ArgumentTypeError(f"Invalid preprocessing JSON: {exc}") from exc

    if not isinstance(step, dict):
        raise ArgumentTypeError("Preprocessing JSON should be an object.")

    if not isinstance(step.get("name"), str) or not step["name"].strip():
        raise ArgumentTypeError("Preprocessing JSON should include a non-empty 'name'.")

    parameters = step.get("parameters")
    if parameters is None:
        step["parameters"] = {}
    elif not isinstance(parameters, dict):
        raise ArgumentTypeError(
            "Preprocessing JSON field 'parameters' should be an object."
        )

    return step


def guess_type_and_cast(value: str):
    """Casts values passed in the command line by guessing their type.

    Types supported: bool, int, float, valid json as string and any other string.
    """
    try:
        return int(value)
    except ValueError:
        pass
    try:
        return float(value)
    except ValueError:
        pass
    if value == "True":
        return True
    if value == "False":
        return False
    try:
        return json.loads(value)
    except json.JSONDecodeError:
        pass
    return value


def get_commandline_request_data(cl_args):
    """Formats an analysis request data object from command line args."""
    parameters = (
        {key: guess_type_and_cast(value) for key, value in cl_args.parameters}
        if cl_args.parameters
        else None
    )
    flags = (
        {key: guess_type_and_cast(value) for key, value in cl_args.flags}
        if cl_args.flags
        else None
    )
    variables = (
        _algorithm_variables({"x": cl_args.x, "y": cl_args.y})
        if cl_args.x or cl_args.y
        else None
    )
    return dict(
        inputdata=dict(
            data_model=cl_args.data_model,
            datasets=cl_args.datasets,
            filters=None,
            variables=variables,
        ),
        algorithm=dict(
            name=cl_args.algorithm,
            y=cl_args.y,
            x=cl_args.x,
            parameters=parameters,
        ),
        preprocessing=cl_args.preprocessing,
        flags=flags,
    )


def get_piped_request_data():
    """Gets an analysis request data object from the stdin. If nothing is piped,
    return empty object."""
    if not sys.stdin.isatty():
        raw_input = sys.stdin.read()
        if not raw_input.strip():
            return {
                "inputdata": {},
                "preprocessing": None,
                "algorithm": {},
                "flags": {},
            }
        piped_input = json.loads(raw_input)
        piped_input["inputdata"]["filters"] = None  # fix for empty string in test case
        try:
            sys.stdin = open(
                "/dev/tty"
            )  # get back stdin in case we need it for debugger
        except OSError:
            pass
        return piped_input
    return {"inputdata": {}, "preprocessing": None, "algorithm": {}, "flags": {}}


def _override_if_provided(base_value, override_value):
    return override_value if override_value not in (None, []) else base_value


def _algorithm_variables(algorithm: dict) -> list:
    return list(dict.fromkeys((algorithm.get("x") or []) + (algorithm.get("y") or [])))


def merge_request_data(data1, data2):
    """Merge request data1 and request data2 prioritizing data2."""
    # merge inpudata
    keys = set(data1["inputdata"].keys()) | set(data2["inputdata"].keys())
    inputdata = {
        key: _override_if_provided(
            data1["inputdata"].get(key, None),
            data2["inputdata"].get(key, None),
        )
        for key in keys
    }

    # merge algorithm
    algorithm_keys = set(data1.get("algorithm", {}).keys()) | set(
        data2.get("algorithm", {}).keys()
    )
    algorithm = {
        key: _override_if_provided(
            data1.get("algorithm", {}).get(key, None),
            data2.get("algorithm", {}).get(key, None),
        )
        for key in algorithm_keys
    }

    cli_algorithm = data2.get("algorithm", {})
    if cli_algorithm.get("x") or cli_algorithm.get("y"):
        inputdata["variables"] = _algorithm_variables(algorithm)

    # merge preprocessing
    preprocessing = _override_if_provided(
        data1.get("preprocessing", None),
        data2.get("preprocessing", None),
    )

    # merge flags
    flags = _override_if_provided(data1.get("flags", None), data2.get("flags", None))

    merged = {
        "inputdata": inputdata,
        "preprocessing": preprocessing,
        "algorithm": algorithm,
        "flags": flags,
    }
    return merged


def do_post_request(algorithm, request_data):
    request_data["algorithm"]["name"] = algorithm
    url = ANALYSIS_URL
    headers = {"Content-type": "application/json", "Accept": "text/plain"}
    response = requests.post(url, data=json.dumps(request_data), headers=headers)
    return response


def print_response(response):
    try:
        print(json.dumps(json.loads(response.text), indent=4))
    except json.decoder.JSONDecodeError:
        print(f"Something went wrong:\n\n{response.text}")


def main(argv):
    if len(argv) == 1 and argv[0] == "--doc":
        pydoc.pager(__doc__)
        return
    cl_args = parse_argv(argv)
    cl_data = get_commandline_request_data(cl_args)
    piped_data = get_piped_request_data()
    request_data = merge_request_data(piped_data, cl_data)
    if cl_args.dry_run:
        print(json.dumps(request_data, indent=4))
    else:
        response = do_post_request(cl_args.algorithm, request_data)
        print_response(response)


if __name__ == "__main__":
    main(sys.argv[1:])
